export const FETCH_MEMBER_LIST = "FETCH_MEMBER_LIST";
export const FETCH_MEMBER_BY_ID = "FETCH_MEMBER_BY_ID";
export const FETCH_TRAINER_LIST = "FETCH_TRAINER_LIST";
export const FETCH_TRAINER_BY_ID = "FETCH_TRAINER_BY_ID";
